language: python
os: linux
install:
- pip install -r test-requirements.txt
script:
- tox -e $TOX_ENV
jobs:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
    env: &1
    - TOX_ENV=py37
  - python: 3.7
    dist: xenial
    sudo: true
    env:
    - TOX_ENV=flake8
  - stage: deploy
    if: branch = master
    python: 3.7
    dist: xenial
    sudo: true
    env: *1
    script: skip
    before_deploy: python ./setup.py sdist
    deploy:
      provider: pypi
      username: __token__
      password:
        secure: kMaCcjsiGBwy97CJls/+5HgwEbFaw4K9QbXzAhNAzztZ4z09wfICvMs9NP8DoVt2sDpB1xWgITPd/azcnpDEx53VGhUbooQBwql8CMgEO+coCsNv8dxYHmruDUt1TwQygeBkcBRevWfqt7Q/Po8wG2aVV/4XVRtrVSLU00KV5aSMSsVsn5lX7xkY6KAzgxFQ7+MxMVyVJF7iLrDe8vHVr1J0Lj8xW77tsz0j/qHcSLWODandOX3Fhh4+uS/IGGrlxqO06hVTICFFAlTLj5vy8HXw5kzhFmgntNy4RLeOmQRwc3huKgD+yJep/ivBrCpJTrHU0i1+DWWKCfH+fFiH0fIGT81fmo98jH44mhBvkACD746nCJjg85QSxbO+3SS3KZUaGcFv/DXcbLhgGWsk2A1Ll7c2GfoY10yjr0QoskgYLG32JcftJhj7Sj68n68ybFuRLh7IZ9qw6p5mjuSs32T6DYW5vaT2FCzMTO6gH3fi8IgDPQp+jM147/yZLiw0Z10BTXtu58uFRo41UHXq8qntsre6AKGnkCIIjhYThPBze52rjyYWU1phHcodrEx311Y4jExrspaOgvdhQXhJwZqgRaiS7Nj8s/QfWvGwuE2TxDxXQcqBD7zf+UGSA1pjqKrZ50quy05e+kGqPcmTc3lyHGcfB6MnPKqcu7AXH3c=
