name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3
      - name: Build a binary wheel and a source tarball
        run: >-
          python ./setup.py sdist
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}